### ISSUE TITLE
Can this be updated to support photo sharing?

### ISSUE THREAD

**Issue by albuquerque** [altryne/google-plus-api#4]
The API works perfectly for sharing plain text or links, but sharing an image optionally with some text does not work.

Could this option be added please?

**Comment by altryne** [comment]
Hey @albuquerque , I'm sorry, but for my time limitations, this project is no longer maintained, I didn't even know it worked. As I moved to 2 step auth with google,and this isn't possible with 2 step, I kind of abandoned it :/
Feel free to take over if you like/can/want.

Sorry to be the bearer of bad news
